name: Continuous Integration

on:
  pull_request:
    branches: ['main']

jobs:
  ci_verification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code From the Repository
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          
      - name: Run Customer Clean Install
        run: npm ci
        working-directory: ./customer
        
      - name: Run Customer Test Script
        run: npm test
        working-directory: ./customer
        
      - name: Run Products Clean Install
        run: npm ci
        working-directory: ./products
        
      - name: Run Products Test Script
        run: npm test
        working-directory: ./products
        
        
      - name: Run Shopping Clean Install
        run: npm ci
        working-directory: ./shopping
        
      - name: Run Shopping Test Script
        run: npm test
        working-directory: ./shopping
        
      
